### ISSUE TITLE
panic when despawning menu

### ISSUE THREAD

**Issue by TomPridham** [nicopap/ui-navigation#15]
not sure if i am doing something incorrectly or if this is a bug. 
i'm creating a start menu, then once someone clicks start, the game starts and the menu gets removed. the default NavigationPlugin has the `listen_nav_requests` system that panics on this line: https://github.com/nicopap/ui-navigation/blob/25bf7e3747392d84476bd4c9c7958efc9effeedd/src/resolve.rs#L439

should i not be completely removing the UI elements or should i unregister the plugin somehow?

**Comment by nicopap** [comment]
Are you using the default systems (the one in `bevy_ui_navigation::systems`: `default_keyboard_input`, `default_mouse_input` or `default_gamepad_input`)? If so that's definitively a bug.

The plugin assumes there is no `NavRequest` to handle, and "helpfully" aborts when encountering one.

The reason for this is: `NavRequest` can only send navigation request. You can't navigate an UI if there is no UI to navigate right? So we tell the user that there is something fishy going on.

But I feel like a panic here might not be ideal, it's probably worth it to downgrade to a simple warning message regardless.

**Comment by TomPridham** [comment]
yeah, i am. i tried adding them only to the menu state before i figured out the issue was in the plugin
```
        app.add_system_set(
            SystemSet::on_update(AppState::MainMenu)
                .with_system(start_button_system)
                .with_system(default_keyboard_input)
                .with_system(default_gamepad_input)
                .with_system(default_mouse_input),
        );
```
an early exit would be better, imo. seems like having that warning print every time the `listen_nav_requests` system runs could get really noisy. maybe print the first time a `None` is encountered to highlight that there could be an issue for people getting started with it

**Comment by nicopap** [comment]
It turns out _there is a way_ to stop the panic. Which I've been using without releasing it was working around a serious bug. You can send a `NavRequest::Locked` or set your start game button as `Focusable::lock()`. This will prevent all navigation input processing. But again, I consider this a bug and a fix is coming within a few hours.

**Comment by TomPridham** [comment]
awesome. thanks for the quick fix!
